changeLogFile=changelogs/db.changelog-master.xml
url=jdbc:postgresql://localhost:5432/liquibase_demo
username=lbuser
password=Sambida@2003
driver=org.postgresql.Driver
classpath=/home/intern8/liquibase/lib/postgresql.jar
logLevel=INFO
logFile=liquibase-run.log
